spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: root
#    hikari:
#      schema: jagire
  jpa:
#    show_sql: true